---
- hosts: all
  tasks:
    - name: 1.Check if EPEL repo is already configured.
      stat: path={{ epel_repofile_path }}
      register: epel_repofile_result
 
    - name: 2.Install EPEL repo.
      yum:
        name: "{{ epel_repo_url }}"
        state: present
      register: result
      when: not epel_repofile_result.stat.exists
 
    - name: 3.Import EPEL GPG key.
      rpm_key:
        key: "{{ epel_repo_gpg_key_url }}"
        state: present
      when: not epel_repofile_result.stat.exists
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest

    - name: copy files
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: start nginx
      service:
          name: nginx
          state: started
