---
- hosts: all
  tasks:

    -name: Crete a new database {{db_schema}}
     mysql_db:
       name: "{{ db_schema }}"
       login_host: "{{ db_host }}"
       login_user: "{{ admin_user }}"
       login_password: "{{ admin_password }}"
       state: present
     register: db_schema_created

    -name: Create a new user '{{ wso2_db_username }}'
     mysql_user:
       name: '{{ wso2_db_username }}'
       password: '{{wso2_db_password }}'
       priv: '{{ db_schema }}.*:ALL,GRANT'
       login_host: "{{ db_host }}"
       login_user: root
       login_password: ""
       host: "{{ item }}"
       append_privs: yes
       state: present
     with_items: "{{ db_access_hosts }}"
     ignore_errors: true
    -name: Initialise databases '{{ db_schema }}'
     mysql_db:
       name: "{{ db_schema }}"
       state: import
       target: "{{ role_path }}/scripts/mysql.sql"
       login_host: "{{ db_host }}"
       login_user: root
       login_password: ""
     when: db_schema_created.changed
       
